### ISSUE TITLE
Error on course confirmation

### ISSUE THREAD

**Issue by kiliankoe** [fsr/ifsr_course_enrollment#20] opened 2015-04-20 22:44 UTC
I'm getting a 404 error on trying to confirm my course. ~~Just as a guess I'm going with the fact that I entered my name as "Kilian Költzsch" and the error is thrown because of the umlaut. Just a guess though.~~

Nevermind, also fails if trying with "Kilian Koeltzsch". Here's a link containing my ultra secret temp password to try out: https://www.ifsr.de/kurse/kurse/confirm/t5gzWGzLGz/KilianKoeltzsch/1

**Comment by fer-rum** [comment] 2015-04-21 11:53
I am not sure, what the link should look like. I tried messing around with it and deleting various stuff, but found no working variant so far.

**Comment by kiliankoe** [comment] 2015-04-21 12:01
I'll update comments all I want as people using github mail notifications should be knowing that they're not seeing updates and check here regardless :P 

Definitely 
![](http://i.giphy.com/KDwFshVZKvs2c.gif)

By the way, because on topic conversation is overrated anyways, I'm supposed to remind you to go shopping tonight.

**Comment by sebschrader** [comment] 2015-04-21 15:21
The link works if you remove the `kurse` once that occurs twice.

https://www.ifsr.de/kurse/confirm/t5gzWGzLGz/KilianKoeltzsch/1

**Comment by fer-rum** [comment] 2015-04-21 16:24
This somehow does not surprise me. So the link generation is broken, not the resolution.

**Comment by fer-rum** [comment] 2015-04-21 16:31
The problem is hardcoded in [View_Participants.py](https://github.com/fsr/ifsr_course_enrollment/blob/master/CManagement/course_manager/views/View_Participants.py), Line 271.

Can someone, who knows how to do this right, please issue a fix?

**Comment by fer-rum** [comment] 2015-05-08 14:13
Closing issue, it works now.

**Closed as completed by fer-rum** 2015-05-08 14:13 UTC
